# Bounding box for the area of interest
LATITUDE_MIN = 32.0
LONGITUDE_MIN = -118.0
LATITUDE_MAX = 33.0
LONGITUDE_MAX = -117.0

# Optional: API key for OpenSky (leave blank or remove if not needed)
# API_KEY = ""

# Directory to store output data files
DATA_DIRECTORY = "./data"

# Logging format (optional)
LOGGING_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output format: "csv" or "json"
# OUTPUT_FORMAT = "csv"
